### ISSUE TITLE
Add a simple example of unit tests that don't crash on mapbox-gl dependencies

### ISSUE THREAD

**Issue by calocan** [uber/react-map-gl#193]
I have react-map-gl working with webpack in a browser environment, but I can't find a simple example of how to write my unit tests so that I don't get an error like:

`Error: Cannot find module 'jsdom'] code: 'MODULE_NOT_FOUND' }`

I'd be happy to install all the dependencies like jsdom and gl in my dev environment if that works and is the recommended, or I'd be happy to mock mapbox-gl in my tests if that's the recommended solution, but the following information about mocking isn't sufficient to replicate:
https://github.com/mapbox/mapbox-gl-js/pull/2753#issuecomment-226572316

Thanks, and please point me in the right direction and close this if there already is such an example.

**Comment by ibgreen** [comment]
@calocan The react-map-gl repository itself runs unit tests under node. When mapbox-gl runs under node it tries to load `jsdom`, `gl` and `sinon` (which are not listed as dependencies by the module), so we had to install these as devDependencies in react-map-gl.

`npm install --save-dev jsdom gl sinon` should do it.

Agree that it could be nice to add a standalone example in the react-map-gl examples folder that shows the same setup for a micro app with react-map-gl as a dependency, to make sure we don't introduce any other node incompatibilities.

**Comment by calocan** [comment]
Thanks @ibgreen. This approach makes sense. I've tried that within your project and mine and in both cases I have the following with the stubbing in the window.js code in mapbox-gl. Perhaps this is just an overly strict setting in tape. Have you seen this, or any idea what might prevent it?

the offending line in wondow.js:

```
    // Stub some CSSOM-related properties that jsdom doesn't implement.
    window.HTMLElement.prototype.clientLeft = 0;
```

the stacktrace:

```
AP version 13
# uncaughtException
not ok 1 TypeError: Cannot set property clientLeft of [object Object] which has only a getter
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot set property clientLeft of [object Object] which has only a getter]
    at: Test.die (/Users/andy/code/react-map-gl/node_modules/tape-catch/index.js:56:10)
    stack: |-
      TypeError: Cannot set property clientLeft of [object Object] which has only a getter
          at restore (/Users/andy/code/react-map-gl/node_modules/mapbox-gl/js/util/window.js:30:45)
          at Object.<anonymous> (/Users/andy/code/react-map-gl/node_modules/mapbox-gl/js/util/window.js:59:18)
          at Module._compile (module.js:541:32)
          at Module.Mp._compile (/Users/andy/code/react-map-gl/node_modules/reify/node/compile-hook.js:10:21)
          at Object.Module._extensions..js (module.js:550:10)
          at Module.load (module.js:458:32)
          at Module.Mp.load (/Users/andy/code/react-map-gl/node_modules/reify/node/runtime.js:16:23)
          at tryModuleLoad (module.js:417:12)
          at Function.Module._load (module.js:409:3)
          at Module.require (module.js:468:17)
  ...

1..1
# tests 1
# pass  0
# fail  1

```

**Comment by ibgreen** [comment]
@calocan Just pulled latest master in react-map-gl, installed and ran `npm test` and got a clean test run.

I use Node 7.4, and install with yarn. I have seen recent versions of `jsdom` cause problems with older versions of Node, maybe it is related to that? Could be worth trying some combinations.

**Comment by cammanderson** [comment]
You can try node 9.9 opposed to 9.10.

**Comment by calocan** [comment]
Thanks @ibgreen, I was able to get it working in my own project by updating to Node 7.5 and wiping out all my globally installed node_modules other than npm.

**Comment by calocan** [comment]
The problem is actually that only browserify works, babel-tape-runner does not.

This works, like react-map-gl uses:
`cross-env NODE_PATH='./source' browserify  -t babelify -t envify source/test/index.js | testron`

This unfortunately does not because it calls code that tries to set a getter (as mentioned above):
`cross-env NODE_PATH='source' babel-tape-runner source/test/index.js`

The problem seems to be that the latter method accesses 
/node_modules/mapbox-gl/js/util/window.js which tries to set a getter, and browserify does not access that code.

**Comment by abmai** [comment]
Hey sorry. I'm just now catching up on this. Was this fixed through a change in your build / script process? Is there anything you see that we can fix in `react-map-gl` itself, @calocan? Thanks!

**Comment by calocan** [comment]
Hi abmai,

Not that I know of. Ever more documentation about testing is always appreciated. I don't personally understand why babel-tape-runner doesn't work. I'm guessing the map-gl library has problems running in node--I know there were effort to mock part of it for test. But documentation saying that tests have to be run with browserify and that jsdom, gl, sinon need to be installed in dev dependencies would help. Thanks.
