### ISSUE TITLE
TypeError: Cannot read property 'recognizeWith' of null

### ISSUE THREAD

**Issue by Stupidism** [uber/react-map-gl#399]
create-react-app
node v6/v8
react-map-gl@^3.1
react@15

This error happens when I run the basic test: `renders without crashing`. 
Now I downgraded react-map-gl to avoid this error.

```
 FAIL  src/App.test.js
  ● renders without crashing

    TypeError: Cannot read property 'recognizeWith' of null
      
      at node_modules/mjolnir.js/dist/event-manager.js:93:21
      at Array.forEach (native)
      at node_modules/mjolnir.js/dist/event-manager.js:92:52
      at Array.forEach (native)
      at new EventManager (node_modules/mjolnir.js/dist/event-manager.js:90:65)
      at InteractiveMap.componentDidMount (node_modules/react-map-gl/dist/components/interactive-map.js:222:26)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:262:25
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:261:11
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:74:22)
      at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:78:26)
      at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:207:25)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:154:16)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/Transaction.js:141:20)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/ReactUpdates.js:87:32)
      at Object.flushBatchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:170:19)
      at ReactDefaultBatchingStrategyTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:207:25)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:154:16)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:95:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:317:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:399:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:420:23)
      at Object.<anonymous>.it (src/App.test.js:7:22)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  ✕ renders without crashing (63ms)

```

**Comment by Pessimistress** [comment]
Fixes published in 3.1.2 patch release.
